In [1]:
# import the numpy library
import numpy as np

## Creating arrays

In [2]:
# this is a list
my_list1 = [1, 2, 3, 4]

# one way of making a numpy array
my_array1 = np.array(my_list1)

In [3]:
my_array1

array([1, 2, 3, 4])

In [4]:
my_list2 = [10, 20, 30, 40]

In [5]:
# combining two lists
my_lists = [my_list1, my_list2]

In [6]:
my_lists

[[1, 2, 3, 4], [10, 20, 30, 40]]

In [7]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [8]:
# the shape of the numpy array, should be 2x4 -> 2 rows, 4 columns
my_array2.shape


(2, 4)

In [9]:
# type of the elements in the array
my_array2.dtype

dtype('int64')

In [10]:
# array of all zeros
np.zeros(5) #type of float numbers -> reason for decimal points

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,), dtype=int) # type of int

array([0, 0, 0, 0, 0])

In [12]:
# matrix array of zeros
np.zeros((3,4)) 


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# matrix of ones, type int
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# empty array
np.empty((5,3))

# this creates an array without initializing entries

array([[4.65470964e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [15]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
# Shift + Tab for help -> start at 5, stop at 50, with step of 5
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

## Using arrays and scalers


In [18]:
my_array1 = np.array([[1,2,3,4],[10,20,30,40]])
my_array1

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [19]:
# this multyplies every number with the number in the same position
my_array1*my_array1

array([[   1,    4,    9,   16],
       [ 100,  400,  900, 1600]])

In [20]:
# we can also do substractions
my_array1 - 5

array([[-4, -3, -2, -1],
       [ 5, 15, 25, 35]])

In [21]:
10 / my_array1

array([[10.        ,  5.        ,  3.33333333,  2.5       ],
       [ 1.        ,  0.5       ,  0.33333333,  0.25      ]])

In [22]:
# we can also do exponential operations
my_array1 ** 3

array([[    1,     8,    27,    64],
       [ 1000,  8000, 27000, 64000]])

## Indexing arrays

In [23]:
my_array1[3] # will throw an error, because the array is 2D

IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
# define a 1D array to play with
arr = np.arange(0,15)
print(arr)
print(arr[8])
print(arr[1:5])

In [ ]:
# all the values from 1 to 5 will be set to 0
arr[1:5] = 0
print(arr)

In [ ]:
arr = np.arange(0,15)
slice_of_arr = arr[0:6]
print(slice_of_arr)

In [ ]:
# update the values in the slice of array and print both them out
slice_of_arr[:] = 0
print(slice_of_arr)
print(arr)


###  The changes also occur in the original array as well, this is because this is only a view of the original array, not a copy.

### If we don't want this to happen, we need to be specific

In [ ]:
arr_copy = arr.copy()
arr_copy

In [ ]:
# 2D arrays, first index row, second is the column
print(my_array1)
print("1st row")
print(my_array1[1])


In [ ]:
print("Index 1 row, index 0 column: {}".format(my_array1[1][0]))

In [ ]:
print("Up to index 2 row, from index 1st to 3th column:\n {}".format(my_array1[:2,1:3]))

In [ ]:
print("First row: {}".format(my_array1[0]))

In [ ]:
print("First column: {}".format(my_array1[:,0]))

In [ ]:
# Create another 2d array with zero values and check it's shape
arr_2d = np.zeros((10,10))
arr_2d.shape 

In [ ]:
for i in range(0, arr_2d.shape[0]):
    print(arr_2d[i])
    arr_2d[i] = i

In [ ]:
print(arr_2d)

In [ ]:
# fancy indexing -> print rows with index 0,2,4,6

print(arr_2d[[0,2,4,6]])
print("---------------------------")
arr_2d[[0,2,4,6]] = 100
print(arr_2d)

In [ ]:
arr_2d[:,5] = 99
arr_2d