In [5]:
import numpy as np

## Creating arrays

In [7]:
# this is a list
my_list1 = [1, 2, 3, 4]

# one way of making a numpy array
my_array1 = np.array(my_list1)

In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [10, 20, 30, 40]

In [10]:
# combining two lists
my_lists = [my_list1, my_list2]

In [11]:
my_lists

[[1, 2, 3, 4], [10, 20, 30, 40]]

In [12]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [14]:
# the shape of the numpy array, should be 2x4 -> 2 rows, 4 columns
my_array2.shape


(2, 4)

In [15]:
# type of the elements in the array
my_array2.dtype

dtype('int64')

In [16]:
# array of all zeros
np.zeros(5) #type of float numbers -> reason for decimal points

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,), dtype=int) # type of int

array([0, 0, 0, 0, 0])

In [19]:
# matrix array of zeros
np.zeros((3,4)) 


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# matrix of ones, type int
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
# empty array
np.empty((5,3))

# this creates an array without initializing entries

array([[4.63672216e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [30]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
# Shift + Tab for help -> start at 5, stop at 50, with step of 5
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])