In [1]:
import numpy as np

## Array transposition

In [2]:
# create an array from 0 to 50 than reshape it to a 10 by 5 matrix
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [3]:
# transpose the matrix
arr.T


array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [4]:
# dot product / shift Tab for more information

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
a = np.array(a)
b = np.array(b)
print(a)
print(b)

[[1 0]
 [0 1]]
[[4 1]
 [2 2]]


In [5]:
np.dot(a,b) # If both `a` and `b` are 2-D arrays, it is matrix multiplication

array([[4, 1],
       [2, 2]])

In [6]:
np.dot(3, 4)

12

In [7]:
arr3d = np.arange(50).reshape(5,5,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [8]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [9]:
# swap
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [10]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

## Universal array functions

In [11]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# we can take square roots of every element of the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
# we can take the exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [14]:
# binary functions require two arrays
A = np.random.randn(10) # random normal distribution
B = np.random.randn(10) 
print(A)
print(B)

[-0.42892281 -2.32239693 -0.25267054  0.84597194 -0.58855913 -1.40176042
  0.73814234  0.27757027  0.07552794  0.86302873]
[ 0.43496694 -0.30817134  0.7583058   0.17238319 -1.22726244  1.25377987
 -1.17701302 -0.37017641 -0.93883609  1.48841533]


In [15]:
# add two arrays together
print(np.add(A,B))

[ 0.00604413 -2.63056827  0.50563526  1.01835513 -1.81582157 -0.14798056
 -0.43887068 -0.09260614 -0.86330815  2.35144406]


In [16]:
# maximum value of one array 
print(np.max(A))

# maximum value of two arrays pairwise
print(np.maximum(A,B))

# same thing for the minumum
print(np.min(A))

# minimum value of two arrays pairwise
print(np.minimum(A,B))

0.8630287278675263
[ 0.43496694 -0.30817134  0.7583058   0.84597194 -0.58855913  1.25377987
  0.73814234  0.27757027  0.07552794  1.48841533]
-2.322396928472754
[-0.42892281 -2.32239693 -0.25267054  0.17238319 -1.22726244 -1.40176042
 -1.17701302 -0.37017641 -0.93883609  0.86302873]


### To see the full list of ufuncs visit the website:
#### https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs